### ISSUE TITLE
NO LICENSE

### ISSUE THREAD

**Issue by niedbalski** [daniel-thompson/ultraeasy#1]
Hello Daniel,

Do you have any License defined for this project?  I think is mandatory
to have one free license (MIT, BSD, GPL, etc) in order to integrate this on debian.

If you have some time to take a look and pick a license for this project, that would be excellent.

Thanks in advance for looking at this issue.

**Comment by daniel-thompson** [comment]
I don't understand this request at all. Every single source file has a header describing the license used _and_ there is a full copy of GPLv3 in the top level directory.
